/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: zordew (https://sketchfab.com/zordewgfx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/f1-tyres-pack-2022-hard-medium-soft-307a0557dde44cf1a7f6f2d1958c383d
Title: F1 TYRES PACK 2022 - HARD - MEDIUM - SOFT
*/

import { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  const groupRef = useRef();
  const [bounce, setBounce] = useState(0);

  useFrame((state, delta) => {
    setBounce(Math.sin(state.clock.elapsedTime * 3) * 0.15); // Adjust the frequency and amplitude
    if (groupRef.current) {
      groupRef.current.position.y = -1.5 + bounce; // Adjust the initial position as needed
    }
  });

  return (
    <group
      {...props}
      ref={groupRef}
      dispose={null}
      position={[-0.5, -1.5, -3]}
      scale={3.5}
    >
      <group position={[-0.921, 0.274, 0.909]} scale={2.182}>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.FRONT_RIM}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials["MEDIUM_TYRE.001"]}
        />
        <mesh geometry={nodes.Object_7.geometry} material={materials.BRAKES} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.SCREW} />
      </group>
      <group position={[-0.921, 0.274, 1.799]} scale={2.182}>
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.FRONT_RIM}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.SOFT_TYRE}
        />
        <mesh geometry={nodes.Object_13.geometry} material={materials.BRAKES} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.SCREW} />
      </group>
      <group position={[-0.921, 0.274, 0.039]} scale={2.182}>
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.FRONT_RIM}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.HARD_TYRE}
        />
        <mesh geometry={nodes.Object_19.geometry} material={materials.BRAKES} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.SCREW} />
      </group>
    </group>
  );
}
